version: "2.3"

services:
  master:
    image: sbeliakou/playpit-labs:kubernetes-master
    container_name: master
    hostname: master
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/containerd
    tmpfs:
      - /run
      - /tmp
    ports:
      - 8022:8022
      - 9090:9090
      - 8081:8081
      - 8001:8001
      - 80:80
      - 443:443
      - 8443:6443
      - 30080-30100:30080-30100
    environment:
      TRAINING: siarhei_beliakou/trainings/prod/kubernetes
      ANALYTICS: ecsc00a05b03.epam.com
    labels:
      project: ${PWD}
      training: kubernetes
      lab: yes
    cpu_count: 1
    privileged: true
    ipc: private
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    networks:
      k8slocal:
        ipv4_address: 172.31.0.2

  node01:
    image: sbeliakou/playpit-labs:kubernetes-node01
    hostname: node01
    container_name: node01
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/containerd
    tmpfs:
      - /run
      - /tmp
    environment:
      TRAINING: siarhei_beliakou/trainings/prod/kubernetes
      ANALYTICS: ecsc00a05b03.epam.com
    labels:
      project: ${PWD}
      training: kubernetes
      lab: yes
    ipc: private
    cpu_count: 1
    privileged: true
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    depends_on:
      - master
    networks:
      k8slocal:
        ipv4_address: 172.31.0.3

networks:
  k8slocal:
    name: playpit-labs-network
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/16
        gateway: 172.31.0.1
